Danhooke inconsistencies
IAMconsortium/common-definitions pull request #26
Opened 2023-09-07 15:21 UTC by danhooke

Updated the R10 regions to be consistent with the IPCC AR6 WGII Annex II R10 regions (https://www.ipcc.ch/report/ar6/wg3/downloads/report/IPCC_AR6_WGIII_Annex-II.pdf). 
There are some small nations which were already in the common-definitions R20 regions but were not included in any of the IPCC R10 regions (e.g. Taiwan, Hong Kong), which I left in. 

Also updated spelling of Czechia at R10 level.
Added Albania to Europe R10 (already in R5 and R9 levels)

2023-09-08 10:23 UTC, danielhuppmann requested changes
Thanks!

Please make sure that the yaml files have a maximum line-length of 88 characters.

Two specific inline suggestions, then good to be merged.

2023-09-08 10:23 UTC, danielhuppmann commented on definitions/region/common.yaml
> +        North Korea, South Korea
Please follow black style with a maximum line width of 88 characters
```suggestion
      countries: China, Hong Kong, Macao, Mongolia, North Korea, South Korea
```

2023-09-08 10:23 UTC, danielhuppmann commented on definitions/region/common.yaml
> +# updated to be consistent with IPCC AR6 WGIII Annex II R10 regions
```suggestion
# updated to be consistent with IPCC AR6 WGIII Annex II R10 regions
# https://www.ipcc.ch/report/ar6/wg3/downloads/report/IPCC_AR6_WGIII_Annex-II.pdf
```

2023-09-08 12:20 UTC, danhooke commented
Thanks, amended

2023-09-11 14:39 UTC, danielhuppmann approved these changes
Thank you!

2023-09-11 14:39 UTC, merged